name: Camp New Test Site
favicon: null
layout_spectrum: 0.28426
typography_spectrum: 0.14529
title: Just a test of Camp New
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0671b7'
    - '#e42727'
    - '#96b2cf'
    - '#262223'
  brandStrength: 0.5960759280715138
  lightness: 0.36002839589491487
  saturation: 0.25010786135680974
  rhythmicContrast: 0.5248718231450766
purpose: []
